#!/bin/bash

set -e

case $(arch) in
    x86_64|amd64)
    ARCH="amd64";;
    aarch64|arm64)
    ARCH="arm64";;
    *)
    echo "Unsupported runner OS, aborting CAS Download"  && exit 1;;
esac

CAS_VERSION=$(get_package_version cas)

curl -fLs \
    "https://github.com/codenotary/cas/releases/download/v1.0.2/cas-v${CAS_VERSION}-linux-${ARCH}" \
    --output ./cas

mv -f "./cas" "/usr/local/bin/cas"
rm -f "./cas"
