#!/bin/bash

set -e

ARCH=$(get_arch docker)

CAS_VERSION=$(get_package_version cas)

curl -fLs \
    "https://github.com/codenotary/cas/releases/download/${CAS_VERSION}/cas-${CAS_VERSION}-linux-${ARCH}" \
    --output ./cas

mv -f "./cas" "/usr/local/bin/cas"
rm -f "./cas"
