#!/bin/bash

set -e

apt-get update
apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common \
    gpg-agent

curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

add-apt-repository "deb https://download.docker.com/linux/debian $(lsb_release -cs) stable"

apt-get update 
apt-get install -y --no-install-recommends \
    docker-ce \
    docker-ce-cli \
    containerd.io

rm -rf /var/lib/apt/lists/*
