#!/bin/bash

set -e

ARCH=$(get_arch)

curl -fLs \
    "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.${ARCH}.tar.xz" \
    | tar -xJ

mv -f "./shellcheck-stable/shellcheck" "/usr/bin/shellcheck"
rm -rf "./shellcheck-stable"
