#!/bin/bash

set -e

VCN_VERSION=$(get_package_version vcn)

curl -Lso /bin/vcn https://github.com/codenotary/vcn/releases/download/${VCN_VERSION}/vcn-${VCN_VERSION}-linux-amd64-static
chmod a+x /bin/vcn
