#!/bin/bash

set -e

VERSION_INFO=$(curl -s https://version.home-assistant.io/dev.json)
HA_ARCH=$(get_arch ha)
QEMU_ARCH=$(get_arch qemu)
SUPERVISOR_SHARE="/mnt/supervisor"

export SUPERVISOR_VERSION="$(echo ${VERSION_INFO} | jq -e -r '.supervisor')"
export SUPERVISOR_IMAGE="$(sed "s/{arch}/${HA_ARCH}/g" <<< "$(echo ${VERSION_INFO} | jq -e -r '.images.supervisor')")"


function cleanup_lastboot() {
    if [[ -f /mnt/supervisor/config.json ]]; then
        echo "Cleaning up last boot"
        sudo jq -rM 'del(.last_boot)' /mnt/supervisor/config.json > /tmp/config.json
        sudo mv /tmp/config.json /mnt/supervisor/config.json
    fi
}

function cleanup_docker() {
    echo "Stopping and removing containers..."
    containers=$(docker ps -a -q)
    if [ -n "$containers" ]; then
        docker stop $containers
        docker rm $containers
    fi
}


validate_devcontainer() {
    local devcontainer_type="$1"

    if ! grep -q "$SUPERVISOR_SHARE" /proc/mounts; then
        echo ""
        echo "WARNING: $SUPERVISOR_SHARE is not a mount! This might cause issues for the"
        echo "Home Assistant Core media and share folders mount propagation option. Make"
        echo "sure to update your .devcontainer."
        echo ""
        if [ "$devcontainer_type" == "apps" ]; then
            echo "You can find the template for apps here:"
            echo "https://github.com/home-assistant/devcontainer/blob/main/apps/devcontainer.json"
            echo ""
        fi
        # For some tests this might be good enough, so create a directory to make things
        # progress.
        sudo mkdir -p "$SUPERVISOR_SHARE"
    fi
}
