#!/bin/bash

set -e

VERSION_INFO=$(curl -s https://version.home-assistant.io/dev.json)
HA_ARCH=$(get_arch ha)
QEMU_ARCH=$(get_arch qemu)
DOCKER_TIMEOUT=30
SUPERVISOR_SHARE="/mnt/supervisor"

export SUPERVISOR_VERSION="$(echo ${VERSION_INFO} | jq -e -r '.supervisor')"
export SUPERVISOR_IMAGE="$(sed "s/{arch}/${HA_ARCH}/g" <<< "$(echo ${VERSION_INFO} | jq -e -r '.images.supervisor')")"


function start_systemd_journald() {
    if ! [ -e /var/log/journal ]; then
        echo "Creating systemd-journald tmpfiles."
        sudo systemd-tmpfiles --create --prefix /var/log/journal
    fi

    if ! pgrep -f systemd-journald; then
        echo "Starting systemd-journald."
        sudo /usr/lib/systemd/systemd-journald &
    fi

    if ! pgrep -f systemd-journal-gatewayd; then
        echo "Starting systemd-journal-gatewayd."
        sudo /usr/lib/systemd/systemd-journal-gatewayd --system 2> /dev/null &
    fi
}


function start_docker() {
    local start_time
    local current_time
    local elapsed_time

    if grep -q 'microsoft-standard\|standard-WSL' /proc/version; then
        # The docker daemon does not start when running WSL2 without adjusting iptables
        sudo update-alternatives --set iptables /usr/sbin/iptables-legacy || echo "Fails adjust iptables"
        sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || echo "Fails adjust ip6tables"
    fi

    echo "Starting docker."
    if stat -f -c %T /var/lib/docker | grep -q overlayfs; then
        echo "Using \"vfs\" storage driver. Bind mount /var/lib/docker to use the faster overlay2 driver."
        storage_driver="vfs"
    else
        storage_driver="overlay2"
    fi
    sudo dockerd --storage-driver="${storage_driver}" > /dev/null 2>&1 &

    echo "Waiting for Docker to initialize..."
    socket_path="/var/run/docker.sock"

    start_time=$(date +%s)
    while [[ ! -S "$socket_path" || ! -r "$socket_path" ]]; do
        current_time=$(date +%s)
        elapsed_time=$((current_time - start_time))

        if [[ $elapsed_time -ge $DOCKER_TIMEOUT ]]; then
            echo "Timeout: Docker did not start within $DOCKER_TIMEOUT seconds."
            exit 1
        fi

        sleep 1
    done

    # It seems that dockerd messes with the terminal somehow, carriage returns (\r)
    # seem not to function properly. Resetting the terminal fixes this.
    stty sane
    echo "Docker was initialized"
}

function stop_docker() {
    local start_time
    local current_time
    local elapsed_time

    # Check if docker pid is there
    if [ ! -f /var/run/docker.pid ]; then
        echo "No pid found for docker"
        return 0
    fi

    echo "Stopping Docker daemon..."
    docker_pid=$(cat /var/run/docker.pid)
    echo "Sending SIGTERM to docker daemon $docker_pid"
    if sudo kill -0 "$docker_pid" 2> /dev/null; then
        start_time="$(date +%s)"

        # Now wait for it to exit
        sudo kill "$docker_pid"
        while sudo kill -0 "$docker_pid" 2> /dev/null; do
            current_time=$(date +%s)
            elapsed_time=$((current_time - start_time))
            if [[ $elapsed_time -ge $DOCKER_TIMEOUT ]]; then
                echo "Timeout while waiting for Docker daemon to exit"
                exit 1
            fi
            sleep 1
        done
    else
        echo "Unable to find Docker daemon process"
    fi
}

function cleanup_lastboot() {
    if [[ -f /mnt/supervisor/config.json ]]; then
        echo "Cleaning up last boot"
        sudo jq -rM 'del(.last_boot)' /mnt/supervisor/config.json > /tmp/config.json
        sudo mv /tmp/config.json /mnt/supervisor/config.json
    fi
}

function cleanup_docker() {
    echo "Stopping and removing containers..."
    containers=$(docker ps -a -q)
    if [ -n "$containers" ]; then
        docker stop $containers
        docker rm $containers
    fi
}

function init_dbus() {
    if pgrep dbus-daemon; then
        echo "Dbus is running"
        return 0
    fi

    echo "Startup dbus"
    sudo mkdir -p /var/lib/dbus
    sudo cp -f /etc/machine-id /var/lib/dbus/machine-id

    # cleanups
    sudo mkdir -p /run/dbus
    sudo rm -f /run/dbus/pid

    # run
    sudo dbus-daemon --system --print-address
}


function init_udev() {
    if pgrep systemd-udevd; then
        echo "udev is running"
        return 0
    fi

    echo "Startup udev"

    # cleanups
    sudo mkdir -p /run/udev

    # run
    sudo /lib/systemd/systemd-udevd --daemon
    sleep 3
    sudo udevadm trigger && sudo udevadm settle
}


function init_os_agent() {
    if pgrep os-agent; then
        echo "os-agent is running"
        return 0
    fi

    sudo os-agent &
}


validate_devcontainer() {
    local devcontainer_type="$1"

    if ! grep -q "$SUPERVISOR_SHARE" /proc/mounts; then
        echo ""
        echo "WARNING: $SUPERVISOR_SHARE is not a mount! This might cause issues for the"
        echo "Home Assistant Core media and share folders mount propagation option. Make"
        echo "sure to update your .devcontainer."
        echo ""
        if [ "$devcontainer_type" == "addons" ]; then
            echo "You can find the template for addons here:"
            echo "https://github.com/home-assistant/devcontainer/blob/main/addons/devcontainer.json"
            echo ""
        fi
        # For some tests this might be good enough, so create a directory to make things
        # progress.
        sudo mkdir -p "$SUPERVISOR_SHARE"
    fi
}